spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: crm-service
  jpa:
    open-in-view: false
  servlet:
    multipart:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

springdoc:
  packages-to-scan: com.crm.web.controller
  paths-to-match: /api/**